/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.111
 * Generated at: 2025-11-05 04:41:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import model.SanPham;
import java.util.*;
import model.KhachHang;
import java.util.*;
import dao.SanPhamDAO;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("dao.SanPhamDAO");
    _jspx_imports_classes.add("model.KhachHang");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.SanPham");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("    ");

    String sort = request.getParameter("sort");

    SanPhamDAO spDAO = new SanPhamDAO();
    ArrayList<SanPham> dsSP = spDAO.selectAll();
    String keyword = request.getParameter("keyword");
    if (keyword != null && !keyword.trim().isEmpty()) {
        ArrayList<SanPham> ketQuaTimKiem = new ArrayList<>();
        for (SanPham sp : dsSP) {
            if (sp.getTenSP().toLowerCase().contains(keyword.toLowerCase())) {
                ketQuaTimKiem.add(sp);
            }
        }
        dsSP = ketQuaTimKiem;
    }

    if (sort != null && !sort.isEmpty()) {
        switch (sort) {
            case "nameAsc":
                Collections.sort(dsSP, new Comparator<SanPham>() {
                    public int compare(SanPham a, SanPham b) {
                        return a.getTenSP().compareToIgnoreCase(b.getTenSP());
                    }
                });
                break;
            case "nameDesc":
                Collections.sort(dsSP, new Comparator<SanPham>() {
                    public int compare(SanPham a, SanPham b) {
                        return b.getTenSP().compareToIgnoreCase(a.getTenSP());
                    }
                });
                break;
            case "priceAsc":
                Collections.sort(dsSP, new Comparator<SanPham>() {
                    public int compare(SanPham a, SanPham b) {
                        return Double.compare(a.getGia(), b.getGia());
                    }
                });
                break;
            case "priceDesc":
                Collections.sort(dsSP, new Comparator<SanPham>() {
                    public int compare(SanPham a, SanPham b) {
                        return Double.compare(b.getGia(), a.getGia());
                    }
                });
                break;
        }
    }

    request.setAttribute("dsSP", dsSP);

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>BookStore</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("  body {\r\n");
      out.write("    font-family: 'Roboto', sans-serif;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
 if ("true".equals(request.getParameter("added"))) { 
      out.write("\r\n");
      out.write("<div class=\"alert alert-success text-center\" role=\"alert\">\r\n");
      out.write("    🛒 Sản phẩm đã được thêm vào giỏ hàng!\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-light px-4\">\r\n");
      out.write("		 <div class=\"container-fluid\">\r\n");
      out.write("			   <nav class=\"navbar navbar-dark bg-dark\">\r\n");
      out.write("				    <div class=\"container\">\r\n");
      out.write("				        <a class=\"navbar-brand\" href=\"index.jsp\">📚 4 Chàng Hiệp Sĩ Mộng Mơ</a>\r\n");
      out.write("				    </div>\r\n");
      out.write("				</nav>\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			    <div class=\"ms-auto d-flex align-items-center gap-3\">\r\n");
      out.write("			      <a href=\"gioHang.jsp\" class=\"btn btn-outline-secondary position-relative\">\r\n");
      out.write("			        🛒 Giỏ hàng\r\n");
      out.write("			        <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger\">\r\n");
      out.write("			          ");
 
			            Integer cartCount = (Integer) session.getAttribute("cartCount");
			            if (cartCount == null) cartCount = 0;
			          
      out.write("\r\n");
      out.write("			          ");
      out.print( cartCount );
      out.write("\r\n");
      out.write("			        </span>\r\n");
      out.write("			        ");
 
			        Object obj = session.getAttribute("kh");
			        KhachHang khachHang = null;
			        if(obj != null){
			        khachHang = (KhachHang)obj;
			        }
			        if(khachHang == null){
			        	
      out.write("\r\n");
      out.write("			        	</a>\r\n");
      out.write("			      <a href=\"dangNhap.jsp\" class=\"btn btn-primary\">Đăng nhập</a>\r\n");
      out.write("			      ");
} else {
      out.write("\r\n");
      out.write("			    	  </a>\r\n");
      out.write("			      <a style = \"while-space: nowrap;\" href=\"dang_xuat\" class=\"btn btn-primary\">Đăng xuất</a>\r\n");
      out.write("			      	\r\n");
      out.write("			      ");
} 
      out.write("\r\n");
      out.write("			      \r\n");
      out.write("			    </div>\r\n");
      out.write("		  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("	<!-- End Navbar -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- Page content -->\r\n");
      out.write("				<div class=\"container mt-4\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<!-- Menu left -->\r\n");
      out.write("						<div class=\"col-lg-3\">\r\n");
      out.write("			  <div class=\"list-group\">\r\n");
      out.write("			  <!-- Thanh tìm kiếm -->\r\n");
      out.write("				<div class=\"mb-3\">\r\n");
      out.write("				  <form action=\"index.jsp\" method=\"get\" class=\"d-flex\">\r\n");
      out.write("				    <input type=\"text\" name=\"keyword\" class=\"form-control me-2\" \r\n");
      out.write("				           placeholder=\"🔍 Tìm sản phẩm...\" \r\n");
      out.write("				           value=\"");
      out.print( request.getParameter("keyword") != null ? request.getParameter("keyword") : "" );
      out.write("\">\r\n");
      out.write("				    <button type=\"submit\" class=\"btn btn-primary btn-sm\">Tìm</button>\r\n");
      out.write("				  </form>\r\n");
      out.write("				</div>\r\n");
      out.write("			    <div class=\"list-group-item active fw-bold text-center\">\r\n");
      out.write("			      THỂ LOẠI\r\n");
      out.write("			    </div>\r\n");
      out.write("			    <a href=\"theLoai.jsp?maTL=1\"  class=\"list-group-item list-group-item-action\">\r\n");
      out.write("			      Sách Khoa học - Viễn tưởng\r\n");
      out.write("			    </a>\r\n");
      out.write("			    <a href=\"theLoai.jsp?maTL=3\" class=\"list-group-item list-group-item-action\">\r\n");
      out.write("			      Sách Kiến thức - Học thuật\r\n");
      out.write("			    </a>\r\n");
      out.write("			    <a href=\"theLoai.jsp?maTL=2\" class=\"list-group-item list-group-item-action\">\r\n");
      out.write("			      Sách Tâm lí - Kỹ năng sống\r\n");
      out.write("			    </a>\r\n");
      out.write("			    <!-- Thanh sắp xếp -->\r\n");
      out.write("					<div class=\"bg-light py-2 px-4 border-top border-bottom d-flex align-items-center justify-content-between\">\r\n");
      out.write("					  <div class=\"fw-bold\">Sắp xếp sản phẩm:</div>\r\n");
      out.write("					  <form action=\"index.jsp\" method=\"get\" class=\"d-flex align-items-center gap-2\">\r\n");
      out.write("					    <select name=\"sort\" class=\"form-select form-select-sm\" onchange=\"this.form.submit()\">\r\n");
      out.write("					      <option value=\"\">-- Chọn cách sắp xếp --</option>\r\n");
      out.write("					      <option value=\"nameAsc\" ");
      out.print( "nameAsc".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">Theo tên (A → Z)</option>\r\n");
      out.write("					      <option value=\"nameDesc\" ");
      out.print( "nameDesc".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">Theo tên (Z → A)</option>\r\n");
      out.write("					      <option value=\"priceAsc\" ");
      out.print( "priceAsc".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">Giá tăng dần</option>\r\n");
      out.write("					      <option value=\"priceDesc\" ");
      out.print( "priceDesc".equals(request.getParameter("sort")) ? "selected" : "" );
      out.write(">Giá giảm dần</option>\r\n");
      out.write("					    </select>\r\n");
      out.write("					  </form>\r\n");
      out.write("					</div>\r\n");
      out.write("			    \r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- End Menu left -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Slider and Products -->\r\n");
      out.write("			<div class=\"col-lg-9\">\r\n");
      out.write("				<!-- Slider -->\r\n");
      out.write("				<div id=\"carouselExampleIndicators\" class=\"carousel slide mb-4\"\r\n");
      out.write("					data-bs-ride=\"true\">\r\n");
      out.write("					<div class=\"carousel-indicators\">\r\n");
      out.write("						<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("							data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\"\r\n");
      out.write("							aria-label=\"Slide 1\"></button>\r\n");
      out.write("						<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("							data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("						<button type=\"button\" data-bs-target=\"#carouselExampleIndicators\"\r\n");
      out.write("							data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"carousel-inner\">\r\n");
      out.write("						<div class=\"carousel-item active\">\r\n");
      out.write("							<img src=\"img/slider/anhbia1.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"carousel-item\">\r\n");
      out.write("							<img src=\"img/slider/anhbia2.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"carousel-item\">\r\n");
      out.write("							<img src=\"img/slider/anhbia3.png\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("						data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("						<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("						<span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("						data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("						<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("						<span class=\"visually-hidden\">Next</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- End Slider -->\r\n");
      out.write("				<!-- Products -->\r\n");
      out.write("				<div class=\"row\">	\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							 ");
 if (dsSP != null && !dsSP.isEmpty()) {
							           for (SanPham sp : dsSP) { 
      out.write("\r\n");
      out.write("							        <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("							            <div class=\"card h-100 shadow-sm\">\r\n");
      out.write("							                <img src=\"");
      out.print( sp.getAnh() );
      out.write("\" class=\"card-img-top\" alt=\"");
      out.print( sp.getTenSP() );
      out.write("\">\r\n");
      out.write("							                <div class=\"card-body text-center\">\r\n");
      out.write("							                    <h6 class=\"card-title\">");
      out.print( sp.getTenSP() );
      out.write("</h6>\r\n");
      out.write("							                    <p class=\"fw-bold text-danger mb-2\">");
      out.print( String.format("%,.0f", sp.getGia()) );
      out.write(" VNĐ</p>\r\n");
      out.write("							                    <div class=\"d-flex justify-content-center gap-2\">\r\n");
      out.write("							                       <form action=\"add-to-cart\" method=\"post\" style=\"display:inline;\">\r\n");
      out.write("													    <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("													    <input type=\"hidden\" name=\"maSP\" value=\"");
      out.print( sp.getMaSP() );
      out.write("\">\r\n");
      out.write("													    <button type=\"submit\" class=\"btn btn-success btn-sm\">\r\n");
      out.write("													        🛒 Thêm vào giỏ\r\n");
      out.write("													    </button>\r\n");
      out.write("													</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							                        <a href=\"chi-tiet?maSP=");
      out.print( sp.getMaSP() );
      out.write("\" class=\"btn btn-outline-primary btn-sm\">\r\n");
      out.write("							                            👁 Xem chi tiết\r\n");
      out.write("							                        </a>\r\n");
      out.write("							                    </div>\r\n");
      out.write("							                </div>\r\n");
      out.write("							            </div>\r\n");
      out.write("							        </div>\r\n");
      out.write("							    ");
 } } else { 
      out.write("\r\n");
      out.write("							<p>Không có sản phẩm nào.</p>\r\n");
      out.write("							");
 } 
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("			\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- End Products -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- End Slider and Products -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Page content -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer class=\"py-3 my-4\">\r\n");
      out.write("		<ul class=\"nav justify-content-center border-bottom pb-3 mb-3\">\r\n");
      out.write("			<li class=\"nav-item\"><a href=\"index.jsp\"\r\n");
      out.write("				class=\"nav-link px-2 text-muted\">Trag chủ</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a href=\"#\"\r\n");
      out.write("				class=\"nav-link px-2 text-muted\">Quy định giao hàng</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a href=\"#\"\r\n");
      out.write("				class=\"nav-link px-2 text-muted\">Quy định trả hàng</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a href=\"#\"	\r\n");
      out.write("				class=\"nav-link px-2 text-muted\">Liên hệ</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a href=\"#\"\r\n");
      out.write("				class=\"nav-link px-2 text-muted\">Blogs</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<p class=\"text-center text-muted\">© 2022 4changhiepsimongmo.vn, Inc</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- End footer -->\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	 \r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
