/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.111
 * Generated at: 2025-11-05 03:45:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import dao.SanPhamDAO;
import model.SanPham;

public final class quanLySanPham_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("dao.SanPhamDAO");
    _jspx_imports_classes.add("model.SanPham");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Quản lý sản phẩm</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"p-4\">\r\n");
      out.write("    <h2 class=\"mb-3 text-center\">Quản lý sản phẩm</h2>\r\n");
      out.write("    <div class=\"text-end mb-3\">\r\n");
      out.write("        <a href=\"themSanPham.jsp\" class=\"btn btn-success\">+ Thêm sản phẩm</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <table class=\"table table-bordered table-striped text-center align-middle\">\r\n");
      out.write("        <thead class=\"table-dark\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Mã SP</th>\r\n");
      out.write("                <th>Tên sản phẩm</th>\r\n");
      out.write("                <th>Giá</th>\r\n");
      out.write("                <th>Ảnh</th>\r\n");
      out.write("                <th>Mô tả</th>\r\n");
      out.write("                <th>Thể loại</th>\r\n");
      out.write("                <th>Tác giả</th>\r\n");
      out.write("                <th>Hành động</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("        ");

            SanPhamDAO dao = new SanPhamDAO();
            ArrayList<SanPham> ds = dao.selectAll();
            for (SanPham sp : ds) {
        
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( sp.getMaSP() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( sp.getTenSP() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( sp.getGia() );
      out.write("</td>\r\n");
      out.write("                <td><img src=\"");
      out.print( sp.getAnh() );
      out.write("\" width=\"70\" height=\"70\" style=\"object-fit:cover;\"></td>\r\n");
      out.write("                <td>");
      out.print( sp.getMoTa() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( sp.getTheLoai().getTenTL() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( sp.getTacGia().getTenTG() );
      out.write("</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <a href=\"suaSanPham.jsp?maSP=");
      out.print( sp.getMaSP() );
      out.write("\" class=\"btn btn-primary btn-sm\">Sửa</a>\r\n");
      out.write("                    <a href=\"xoaSanPham?maSP=");
      out.print( sp.getMaSP() );
      out.write("\" class=\"btn btn-danger btn-sm\"\r\n");
      out.write("                       onclick=\"return confirm('Bạn có chắc muốn xóa sản phẩm này không?')\">Xóa</a>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
